port:

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  user: root
  pass:

library:

captcha:
  breaker_url:
  new_breaker_url:

zf:
  url:
  main_url:
  bk_url:

canteen:

log:
  level: "info" #level有四个等级，主要使用debug和info
  name: "funnel"
  rotationTime: 1 #分割周期
  maxAge: 14 #存活周期