Name: funnel-api
Host: 0.0.0.0
Port: 8888
biz:
  zf:
    public:
      username: "mjj"
      password: "114514"
    base_url: "http://www.gdjw.zjut.edu.cn/jwglxt/"
    session_pool:
      max_size: 64         # 池容量
      ttl_minute: 30       # cookie 过期时间
      fill_workers: 3      # 并发填充数